esphome:
  name: sensor_biocube32
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "REDACTED"
  password: "REDACTED"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sensor Biocube32"
    password: "REDACTED"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

# Example configuration entry
dallas:
  - pin: D7

# Individual Sensors
sensor:
  - platform: dallas
    address: 0xD301191A09765828
    name: "Biocube 32"
    filters:
      offset: -0.3
